### ISSUE TITLE
sqlite3.OperationalError: no such table: mapping

### ISSUE THREAD

**Issue by oorejola** [jcklie/wikimapper#10]
Jan,

I followed your instructions for installation on my machine using ` pip install wikimapper `. When I run the command
 `$ wikimapper title2id index_enwiki-latest.db Germany` 

 I receive the error 
`sqlite3.OperationalError: no such table: mapping`.

 Do you know how I can remedy this issue? 

Many thanks in advance!

-Oliver

**Comment by jcklie** [comment]
Hi, did you download or create an index before running that command? For me it works when I download a [precomputed index ](https://github.com/jcklie/wikimapper#precomputed-indices) and then run the command with the correct filename:

```bash
$ pip install wikimapper
$ wget https://public.ukp.informatik.tu-darmstadt.de/wikimapper/index_enwiki-20190420.db
$ wikimapper title2id index_enwiki-20190420.db Germany
Q183
```

**Comment by jcklie** [comment]
I will close this due to inaction, please reopen if this error still persists.
