### ISSUE TITLE
Error when loading the file if it contains invalid UTF-8

### ISSUE THREAD

**Issue by wannaphong** [jcklie/wikimapper#12]
Hello! I just downloaded latest wikidata from wikiadate and I found the script can't load the file when line 189 in wikimapper/processor.py, so I fixed the issue by #11.

- Python: 3.8
- Ubuntu 22.04 (docker)

**Comment by jcklie** [comment]
I was unable to reproduce your issue, which language code did you use to create an index from?

**Comment by wannaphong** [comment]
> I was unable to reproduce your issue, which language code did you use to create an index from?

I use `th` for Thai language.

**Comment by jcklie** [comment]
I was able to reproduce the issue, your fix worked, thanks for the PR! I also released a new version with it just now.
