### ISSUE TITLE
Error while connecting to sqlite no such table: mapping

### ISSUE THREAD

**Issue by mariaBio** [jcklie/wikimapper#6]
Dear Jans!

First of all, thank you very much for making the wikimapper tool available.
Just installed it according to the instructions and tried to run, but got the following error:
>>> from wikimapper import WikiMapper
>>> mapper = WikiMapper("index_enwiki-latest.db")
>>> wikidata_id = mapper.title_to_id("Python_(programming_language)")
Error while connecting to sqlite no such table: mapping

In the directory I do have the db with which the Mapper is initialised: 
index_enwiki-latest.db

Would you have any suggestion on how to overcome the issue?

Thank you very much for your kind help!
Maria

**Comment by jcklie** [comment]
Hi,
I tested it on a fresh installation and it worked for me. Are you sure the db file is where you expect it? Did you download one of the precomputed indices or one of your own? Does it work via the command line, e.g. `wikimapper id2titles index_enwiki-latest.db Q183`?

**Comment by mariaBio** [comment]
Hi,

Thank you very much for your speedy reply. 
It was all my fault - path to a non-empty database. 
Now everything works as illustrated on your github page!

Thank you again and sorry for disturbing!
Maria

**Comment by jcklie** [comment]
Happy to help!
